config/routes.rb
Ipn::Application.routes.draw do
  resources :paypal_payment_notifications

  root :to => 'paypal_payment_notifications#index'
end

app/models/paypal_payment_notification.rb
class PaypalPaymentNotification < ActiveRecord::Base
  serialize :params
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/paypal_payment_notifications_controller.rb
class PaypalPaymentNotificationsController < InheritedResources::Base
  actions :index, :show, :create

  protect_from_forgery :except => [:create]

  def create
    PaypalPaymentNotification.create!(
      :params => params,
      :status => params[:payment_status],
      :paypal_transaction_id => params[:txn_id],
      :invoice => params[:invoice],
      :raw_post => request.raw_post
    )
    render :nothing => true
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/paypal_payment_notifications_helper.rb
module PaypalPaymentNotificationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ipn</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/paypal_payment_notifications/_form.html.haml
= form_for @paypal_payment_notification do |f|
  -if @paypal_payment_notification.errors.any?
    #error_explanation
      %h2= "#{pluralize(@paypal_payment_notification.errors.count, "error")} prohibited this paypal_payment_notification from being saved:"
      %ul
        - @paypal_payment_notification.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :params
    = f.text_area :params
  .field
    = f.label :status
    = f.text_field :status
  .field
    = f.label :paypal_transaction_id
    = f.text_field :paypal_transaction_id
  .field
    = f.label :invoice
    = f.text_field :invoice
  .field
    = f.label :raw_post
    = f.text_area :raw_post
  .actions
    = f.submit 'Save'

app/views/paypal_payment_notifications/edit.html.haml
%h1 Editing paypal_payment_notification

= render 'form'

= link_to 'Show', @paypal_payment_notification
\|
= link_to 'Back', paypal_payment_notifications_path

app/views/paypal_payment_notifications/index.html.haml
%h1 Listing paypal_payment_notifications

%table
  %tr
    %th Params
    %th Status
    %th Paypal transaction
    %th Invoice
    %th Raw post
    %th Actions

  - @paypal_payment_notifications.each do |paypal_payment_notification|
    %tr
      %td= paypal_payment_notification.params
      %td= paypal_payment_notification.status
      %td= paypal_payment_notification.paypal_transaction_id
      %td= paypal_payment_notification.invoice
      %td= paypal_payment_notification.raw_post
      %td= link_to 'Show', paypal_payment_notification

app/views/paypal_payment_notifications/new.html.haml
%h1 New paypal_payment_notification

= render 'form'

= link_to 'Back', paypal_payment_notifications_path

app/views/paypal_payment_notifications/show.html.haml
%p#notice= notice

%p
  %b Params:
  = @paypal_payment_notification.params
%p
  %b Status:
  = @paypal_payment_notification.status
%p
  %b Paypal transaction:
  = @paypal_payment_notification.paypal_transaction_id
%p
  %b Invoice:
  = @paypal_payment_notification.invoice
%p
  %b Raw post:
  = @paypal_payment_notification.raw_post

= link_to 'Edit', edit_paypal_payment_notification_path(@paypal_payment_notification)
\|
= link_to 'Back', paypal_payment_notifications_path